### ISSUE TITLE
Feature request:  Optionally populate sub-messages

### ISSUE THREAD

**Issue by meadoch1** [tony612/protobuf-elixir#13]
When a message has fields which are in turn messages it would be handy to optionally have `.new` create the sub-messages all the way through the hierarchy defined in the message structure.

**Comment by tony612** [comment]
But you may have this kind problem https://github.com/tony612/protobuf-elixir/issues/11

**Comment by meadoch1** [comment]
Even if it only instantiated deterministic contents (e.g. oneof and map wouldn't be populated) that would be helpful; however, I understand if this is niche enough that it doesn't make sense for the library.

**Comment by meadoch1** [comment]
Also, the messages I've needed this for are  strictly structured like a tree with deterministic termination points, and not recursive.  I can see where recursive relationships would be a problem.
