### ISSUE TITLE
Good work!

### ISSUE THREAD

**Issue by karlseguin** [tony612/protobuf-elixir#2]
Just wanted to say thanks. I was going to embark on something almost exactly like this after seeing how exprotobuf was implemented. Even without a `protoc` generator, I'll happily manually setup the DSL for the saner and much more efficient approach you're taking. Anxious for `oneof` to land :)

**Comment by tony612** [comment]
@karlseguin Glad to hear that! Please let me know if there's any problem for you. I'll try to fix ASAP 😬

**Comment by meadoch1** [comment]
Hi Tony.  I'm also very interested in using this instead of exprotobuf.  We do need oneofs though.  Do you have an estimate of when you expect them to be ready for use?

**Comment by tony612** [comment]
@meadoch1 I'm working on it now! I hope to finish it within these two days. Will ping you when it's done.😄

**Comment by meadoch1** [comment]
Wow, that's great news.  Thanks!  Since you're doing maps and oneof can I assume it's proto3 compatible otherwise too?

**Comment by tony612** [comment]
@meadoch1 Yes. But I think I'd better add more tests about compatibility :)

**Comment by meadoch1** [comment]
👍

**Comment by meadoch1** [comment]
@tony612 how is the progress on oneof coming?

**Comment by tony612** [comment]
It’s finished on master branch but not in a version on hex.

**Comment by meadoch1** [comment]
That's good news.  I'll pull it and give it a try soon.  Thanks!

**Comment by tony612** [comment]
@meadoch1 OK. I can release a new version if you think there're no serious issues. It is worth mentioning that the usage for oneof is a little different:
```
TestMsg.Oneof.new(first: {:a, 42})
```
In this example, `:first` is the oneof field, `:a` is the actual field and `42` is the actual value. This can be refered from the tests, like https://github.com/tony612/protobuf-elixir/blame/master/test/protobuf/protoc/integration_test.exs#L22. Please give some feedback about this design. It's not easy to decide how to implement oneof in dynamic type language like Elixir.

I'll add documents after my holiday ends these days.

**Comment by meadoch1** [comment]
I'll see what I can shake out of it, but it may be a couple of weeks before I get it vetted well.  I'll reply back here with results.

**Comment by meadoch1** [comment]
I've gotten a chance to work with the library some at this point, porting an app from exprotobuf to your library.  I found using protobuf-elixir to be good and love that it validates on encoding.  That solves several problems that we've been encountering.  The Oneof syntax is no more unwieldy than in exprotobuf and I think simply reflects that Oneofs are more complex than simply nested messages.  Unfortunately I don't have a good thought on how to structure them differently.

I'd think it's good and worth cutting a new version to make official.  Thanks for all your work on this.
