### ISSUE TITLE
Protobuf module conflicts with exprotobuf

### ISSUE THREAD

**Issue by cjab** [tony612/protobuf-elixir#21]
The top level module name `Protobuf` is also the top level module for exproto (https://github.com/bitwalker/exprotobuf/blob/master/lib/exprotobuf.ex). This makes it difficult to use protobuf-elixir in projects that also have a secondary dependency on exproto. I know it's a lot to ask to rename it but I wanted to bring it up here. It's likely that others have or will run into this also.

In my case I'm unable to use https://github.com/peburrows/diplomat because of it's dependency on exproto.

**Comment by amatalai** [comment]
I had similar problem, but based on how libs are named on hex and how `.ex` files are named, the problem is that exprotobuf is using wrong namespace for modules.

**Comment by tony612** [comment]
It's hard to solve this problem for the moment because Erlang/Elixir doesn't support the features like importing modules. I found a similar issue https://github.com/elixir-lang/elixir/issues/5232
