### ISSUE TITLE
Support Google Protobuf Timestamp type

### ISSUE THREAD

**Issue by zentetsukenz** [tony612/protobuf-elixir#24]
First of all, I must thank you for this great GRPC lib for Elixir. The features are almost there. 

However, one of well known type is still missing, Timestamp. I'd already implement the `Google.Protobuf.Timestamp` type and would like to contribute back but not sure where I should put this chunk of code into.

```elixir
defmodule Google.Protobuf.Timestamp do
  @moduledoc false

  use Protobuf, syntax: :proto2

  @type t :: %__MODULE__{
    seconds: integer,
    nanos: integer
  }

  defstruct [:seconds, :nanos]

  field :seconds, 1, optional: true, type: :int64
  field :nanos, 2, optional: true, type: :int32
end
```

This implement Timestamp type according to Google Protobuf Timestamp type message definition [here](https://github.com/google/protobuf/blob/master/src/google/protobuf/timestamp.proto)

If you agree with this implementation, I will open PR as soon as possible.

**Comment by tony612** [comment]
Thank you. But I prefer not. This lib is the implementation of protobuf, I don't think adding Google's proto definitions in this lib is a good idea.

**Comment by tony612** [comment]
By looking into other official implementations(https://developers.google.com/protocol-buffers/docs/reference/overview), I think it's ok to include it in this lib. Could you place the proto file and generated file in `lib/google/protobuf`?

**Comment by zentetsukenz** [comment]
@tony612 Sure! I will do open a PR for this. However, I'm still unsure that I understand your solution. This is what I'm currently understand. Create a new file in `lib/google/protobuf/`. Named it `timeout.pb.ex` and put the code snippet above into this file.

I'm not sure about this because I saw that there are many google file descriptor definition in `lib/protobuf/protoc/descriptor.pb.ex`. So, I think I would have to do things similar to this by putting the file in `lib/protobuf/protoc` folder.

Thank you in advance.

**Comment by tony612** [comment]
@zentetsukenz Yes. And I've moved `descriptor.pb.ex` and `plugin.pb.ex` to `lib/google/protobuf`

**Comment by zentetsukenz** [comment]
@tony612 PR https://github.com/tony612/protobuf-elixir/pull/25 opened, please have a look when you have time. Thank you for your consideration.
