### ISSUE TITLE
Error when parsing services without an explicit package name.

### ISSUE THREAD

**Issue by obmarg** [tony612/protobuf-elixir#29]
Similar to #27 - I'm getting a crash when I try to compile the following proto file:

```proto
syntax = "proto3";

message RenderRequest {
}

message RenderResult {
    string html = 1;
}

service ElmRender {
    rpc Render(RenderRequest) returns (RenderResult);
}
```

If I add `package elm_render;` it works fine.

**Comment by tony612** [comment]
Try updating to the latest version?

**Comment by obmarg** [comment]
@tony612 I'm seeing this with 0.5.3, which I believe is the latest version?

**Comment by tony612** [comment]
I see. I’ll look into this later.

**Comment by tony612** [comment]
@obmarg Could you verify if this problem has been fixed on master?

**Comment by obmarg** [comment]
@tony612 are there any instructions for running from a non-release?  I only know how to run w/ an escript installed from hex.

**Comment by tony612** [comment]
@obmarg `mix escript.install github tony612/protobuf-elixir`. You can view doc via `mix help escript.install`

**Comment by tony612** [comment]
If it works, I can release a new version.

**Comment by obmarg** [comment]
@tony612 thanks - I'll try and test that tonight when I get home

**Comment by obmarg** [comment]
@tony612 looks like your fix worked.  thanks a lot!
