### ISSUE TITLE
protoc --elixir_out=./lib helloworld.proto

### ISSUE THREAD

**Issue by Saber2016** [tony612/protobuf-elixir#42]
可以介绍一下在Windows系统上怎么安装这个吗？我尝试用macOS的教程，运行到：
proto>protoc --elixir_out=./lib helloeworld.proto 时候总是提示我：--elixir_out: protoc-gen-elixir: 系统找不到指定的文件。但实际上在上一步我是生成了这个文件的。
>mix escript.install hex protobuf
Failed to fetch record for 'hexpm/protobuf' from registry (using cache)
:timeout
Resolving Hex dependencies...
Dependency resolution completed:
New:
[32m  protobuf 0.5.4[0m
* Getting protobuf (Hex package)
Request failed (:timeout)
If this happens consistently, adjust your concurrency and timeout settings:

    HEX_HTTP_CONCURRENCY=1 HEX_HTTP_TIMEOUT=120 mix deps.get
  Fetch failed. Using locally cached package (c:/Users/Paul.Qing/.hex/packages/hexpm/protobuf-0.5.4.tar)
All dependencies up to date
Compiling 21 files (.ex)
Generated protobuf app
Generated escript protoc-gen-elixir with MIX_ENV=prod
Found existing entry: c:/Users/Paul.Qing/.mix/escripts/protoc-gen-elixir。

希望收到回复，谢谢

**Comment by tony612** [comment]
I think you have to put `protoc-gen-elixir` in your PATH.
