### ISSUE TITLE
[question] Generate proto files according to package

### ISSUE THREAD

**Issue by mwillema** [tony612/protobuf-elixir#49]
Is there a way to generate the proto files into a directory structure matching the proto package ?

For instance I have a proto definition placed in `priv/proto` such as:
```
syntax = "proto3";
package company.my_messages;
...
```

When I compile the messages using `protoc --elixir_out=./lib priv/proto/*.proto` I'd like the files to be generated in `lib/company/my_message`.

**Comment by tony612** [comment]
You can add argument `-I priv/proto`
