### ISSUE TITLE
gRPC rpc call should be snake_case in Elixir

### ISSUE THREAD

**Issue by Sgiath** [tony612/protobuf-elixir#57]
First of all, thanks for your work! It is amazing.

I have one issue though:
According to Protocol Buffers style guide https://developers.google.com/protocol-buffers/docs/style#services `rpc` calls in `Service` section should CamelCased:
`rpc SayHello(HelloRequest) returns (HelloResponse);`
which is then translated to following Elixir code:
`rpc :SayHello, HelloRequest, HelloResponse`
and we can use it in the server as:
```
defmodule HelloExample.Server do
  use GRPC.Server, service: HelloExample.Service

  def SayHello(request, stream) do
    ...
  end
end
```
but Elixir functions should be snake_cased (see https://hexdocs.pm/elixir/master/naming-conventions.html#casing ).

If I rename `.proto` definition to snake_case `protoc-gen-lint` is complaining if I rename it to CamelCase Elixir is complaining.

Is it possible to convert the CamelCased proto definition to snake_case Elixir definition so both linters are satisfied?

**Comment by tony612** [comment]
You need to define `say_hello` in your servers. The name in `rpc` macro is just kept same with that in proto.

**Comment by Sgiath** [comment]
Oh so I can define function `say_hello` even though I have in my service `rpc :SayHello, SayHelloRequest, SayHelloResponse` and it will link them correctly?

**Comment by tony612** [comment]
@Sgiath Yes. You are right.

**Comment by Sgiath** [comment]
OK, I didn't know that.

Closing the issue
