### ISSUE TITLE
How to get atom as value of enum field

### ISSUE THREAD

**Issue by predrag-rakic** [tony612/protobuf-elixir#6]
If I define message:
```
message ExitStatus {
  enum Status {
    PASS = 0;
    FAIL = 1;
  }

  Status status = 1;
}
```

And later in the code
```
...
v = ExitStatus.decode(...)
```
Is there a way to get `:PASS` or `:FAIL` out of `v`?

Thank you.

**Comment by tony612** [comment]
This is not supported now, only atom => number is supported. But I can add this feature later today.

**Comment by tony612** [comment]
It's supported now by `key/1` function like
```
TestMsg.EnumFoo.key(2)
```
Please use 0.3.3

**Comment by predrag-rakic** [comment]
@tony612 thank you
