### ISSUE TITLE
float and NaN/Infinity values

### ISSUE THREAD

**Issue by llxff** [tony612/protobuf-elixir#60]
Hello,

I found that it is not possible to work with NaN, Infinity, -Infinity values for float. Erlang doesn't have such values but they can be encoded in Protobuf messages. Currently, decoding of messages with such values fails with MatchError exception. Do you have some plans to support them?

**Comment by tony612** [comment]
@llxff I can support them, but we should figure out what to use for `nan`, `infinity` and `-infinity`. I thought about atom before, but it's still not very good.

**Comment by tony612** [comment]
I guess it's OK to decode it as atom like `:infinity` now so you won't get exceptions. But you still need to handle float carefully by yourself. Is this OK for you?

**Comment by llxff** [comment]
I thought the same, at least it is better than exception 🙂

**Comment by tony612** [comment]
Could you try this PR? https://github.com/tony612/protobuf-elixir/pull/62

**Comment by llxff** [comment]
Works for me, checked `double` and `float` 👍

**Comment by tony612** [comment]
I merged that PR. You can use the master for the moment. I'll release a new version on hex later.

**Comment by llxff** [comment]
Great, thank you very much!
