### ISSUE TITLE
protoc --elixir_out=./lib helloworld.proto

### ISSUE THREAD

**Issue by mehdi514** [tony612/protobuf-elixir#61]
![Capture](https://user-images.githubusercontent.com/38223998/61874425-6a003900-aef9-11e9-9b77-e37b0beab40b.PNG)

**Comment by tony612** [comment]
Where is your `helloworld.proto`? You need to specify a path to your proto files.

**Comment by mehdi514** [comment]
![Screenshot (225)](https://user-images.githubusercontent.com/38223998/62461965-3d6cdc80-b797-11e9-98cd-1248641d382d.png)
helloworld.proto is specified and still its showing the error! 
Can you please help me? I'm new on it and if I'm doing wrong then help me the correct way to learn it.
