### ISSUE TITLE
Feature Request: support google.rpc.Status.Details

### ISSUE THREAD

**Issue by joelmarty** [tony612/protobuf-elixir#64]
The gRPC error model has the ability to embed any kind of message in the status of a RPC (see [this doc](https://cloud.google.com/apis/design/errors#error_model)).

It is a feature that would be quite useful to convey error details since custom status codes are not documented in .proto files.

**Comment by tony612** [comment]
google's protos are just normal protobuf. You can directly use them after generating the code.
```
iex(2)> Google.Rpc.Status.new(details: [%{type_url: "foo", value: "Custom error"}])
%Google.Rpc.Status{
  code: 0,
  details: [%Google.Protobuf.Any{type_url: "foo", value: "Custom error"}],
  message: ""
}
```
