### ISSUE TITLE
Value that is too big for an uint32 is successfully encoded and decoded

### ISSUE THREAD

**Issue by NAR** [tony612/protobuf-elixir#67]
I have this protocol buffer definition:
```
syntax = "proto3";

message Uint {
  uint32 u = 1;
}
```
When I create a value that's too big for a 32 bit unsigned integer, encoding and decoding surprisingly works:
```
iex(10)> Uint.decode(Uint.encode(Uint.new(u: 12345678901234567890)))
%Uint{u: 12345678901234567890}
```
If I use a different library to decode the result, I get a shorter value:
```
iex(9)> Uint.encode(Uint.new(u: 12345678901234567890))
<<8, 210, 149, 252, 216, 206, 177, 170, 170, 171, 1>>
iex(10)> Proto2Test.Uint.decode(<<8, 210, 149, 252, 216, 206, 177, 170, 170, 171, 1>>)
%Proto2Test.Uint{u: 3944680146}
```
I think the `3944680146` value looks better, definitely fits into a 32 bit unsigned integer.

**Comment by tony612** [comment]
@NAR I sent a PR to validate the range. How do you think about it? Another way is still accepting the bigger/smaller values and returning wrong but valid values. I like raising errors in this case because some bugs can be avoided.

**Comment by NAR** [comment]
I tried it and get a `FunctionClauseError`, so it looks OK. Decode also doesn't return too big value. The PR also looks good.

**Comment by tony612** [comment]
Changed the error a little and merged. Thank you!
