### ISSUE TITLE
Error trying to find proto file

### ISSUE THREAD

**Issue by ealmz** [tony612/protobuf-elixir#69]
I have my proto file in on the top level of my directory. When I run this: `protoc --elixir_out=./lib rpc.proto`, I get the following error:
```
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--elixir_out: protoc-gen-elixir: Plugin failed with status code 1.
```

I've tried many variations of appending to my path without luck. The latest one is: `export PATH=/Users/emmyalmaraz/.mix/escripts/bin:$PATH`

**Comment by whatyouhide** [comment]
@ealmz how did you install protobuf-elixir?

**Comment by whatyouhide** [comment]
@ealmz once you do that, do you have `~/.mix/escripts/protoc-gen-elxiir` available? The `bin` part shouldn't be there.

**Comment by whatyouhide** [comment]
You should have `~/.asdf/shims` in the path, then make sure that you install `mix escript.install hex protobuf` in the current version you're using and then call `asdf reshim`.
