### ISSUE TITLE
What's providing protoc-gen-elixir ?

### ISSUE THREAD

**Issue by arnaud-lb** [tony612/protobuf-elixir#7]
From the readme:

> Install protoc plugin protoc-gen-elixir for Elixir . NOTE: You have to make sure protoc-gen-elixir(this name is important) is in your PATH.

What project is providing protoc-gen-elixir ? Is it gRPC, this project, or an other independent project ?

**Comment by tony612** [comment]
The README gives the answer 😁(this project):
```
$ mix escript.install hex protobuf
```

**Comment by arnaud-lb** [comment]
Ho wow, thanks :) Somehow my mind refused to see that line :)

**Comment by nathanl** [comment]
I had the same question.

>    Install protoc plugin protoc-gen-elixir for Elixir . NOTE: You have to make sure protoc-gen-elixir(this name is important) is in your PATH.

> $ mix escript.install hex protobuf

The command doesn't say `escript.install hex protoc-gen-elixir`, so I thought it was a prerequisite for the command.
