### ISSUE TITLE
Merging cowboy/cowlib changes upstream ?

### ISSUE THREAD

**Issue by bryanhuntesl** [tony612/protobuf-elixir#78]
Are there any plans to merge the cowboy/cowlib forks upstream? I'm thinking the forks might miss out on security fixes/new functionality over time.

**Comment by whatyouhide** [comment]
I'm confused, where is cowboy/cowlib used in protobuf-elixir? 😕

**Comment by bryanhuntesl** [comment]
Apologies - I had two windows and 50 tabs open - I should have posted that question on elixir-grpc/grpc repository - I'll close and re-ask there.
