### ISSUE TITLE
one question for encoder?

### ISSUE THREAD

**Issue by redink** [tony612/protobuf-elixir#8]
https://github.com/tony612/protobuf-elixir/blob/5f8da613191501d560dce00087cb500f654a991a/lib/protobuf/encoder.ex#L54

For example, I need encode
```
[ [], [] ]
```

just like : 

```
syntax = "proto3";

message TListList {
    repeated TList listlist = 1;
}

message TList {
    repeated string ele = 1;
}
```

But, after encode I got

```
// ==>
// ""
```

and after decode it, I got 

```
// ==>
// [ ]
```

It's not the result I need.

**Comment by tony612** [comment]
fixed in 0.3.4
