### ISSUE TITLE
v0.7.1 erroneously enforces source code ordering of modules

### ISSUE THREAD

**Issue by c-h-** [tony612/protobuf-elixir#84]
Just upgraded from 0.6.3 to 0.7.1.

On 0.6.3, I could have generated Elixir protobuf files like this:
```
defmodule Test.MyMessage do
  @moduledoc false
  use Protobuf, syntax: :proto3

  @type t :: %__MODULE__{
          type: atom | integer
        }
  defstruct [
    :type
  ]
  field :type, 1, type: Test.MessageEnum, enum: true
end

defmodule Test.MessageEnum do
  @moduledoc false
  use Protobuf, enum: true, syntax: :proto3

  field :ZERO, 0
  field :ONE, 1
  field :TWO, 2
end
```

Compiling the app with 0.7.1 gives errors like these when compiling the above generated protobuf files:
```
== Compilation error in file /.../file.pb.ex ==
** (UndefinedFunctionError) function Test.MessageEnum.key/1 is undefined (module Test.MessageEnum is not available)
    Test.MessageEnum.key(0)
    lib/protobuf/dsl.ex:33: anonymous fn/2 in Protobuf.DSL."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding macro: Protobuf.DSL.__before_compile__/1
    /.../file.pb.ex:1: Test.MyMessage (module)
```

Going back to 0.6.3 fixes the issue, as does re-ordering the source code like so:
```
defmodule Test.MessageEnum do
  @moduledoc false
  use Protobuf, enum: true, syntax: :proto3

  field :ZERO, 0
  field :ONE, 1
  field :TWO, 2
end

defmodule Test.MyMessage do
  @moduledoc false
  use Protobuf, syntax: :proto3

  @type t :: %__MODULE__{
          type: atom | integer
        }
  defstruct [
    :type
  ]
  field :type, 1, type: Test.MessageEnum, enum: true
end
```

Given this code is generated, re-ordering it should not be necessary.

On glancing at the recent changes, I'd guess that the problem is coming from here: https://github.com/tony612/protobuf-elixir/commit/cfb026b8f00dbe1db66d375748847dbc5de13df9#diff-8b2c39dee263c97e81c3eb547e5012d8

This appears to be a bug to me since Elixir code shouldn't care about the ordering of modules within source code during compilation. Thanks!

**Comment by tony612** [comment]
Please use latest protoc plugin by `mix escript.install hex protobuf` and regenerate the code. Ordering of modules in one file does matter!
