### ISSUE TITLE
protoc package name and path

### ISSUE THREAD

**Issue by karlseguin** [tony612/protobuf-elixir#9]
1. Is there a reason package names are underscored? 
package Foo.Bar --> defmodule Foo_Bar, why?

2. Can it listen to --elixir_out and not append a proto sub-folder?

**Comment by tony612** [comment]
1. Because I want to distinguish the package name and message name. If you have a name like `Foo.Bar.Baz`, how can you tell what's the package name?
2. I believe it's a behavior of protoc. If you have file `foo/bar.proto` and call `protoc --elixir_out=./ foo/bar.proto`, it will create a file `foo/bar.pb.ex`. But if you have file `foo/bar.proto` and call `protoc -I foo/ --elixir_out=./ foo/bar.proto`, it will create a file `bar.pb.ex`

**Comment by predrag-rakic** [comment]
Hi Tony,

I think dot in package directive should not be replaced with underscore for 2 reasons:
1. in other languages `package` directive generates module hierarchy. For example 

```
package Foo.Bar;

message Baz {...}
```
is expanded to:
- in C++ 
```
namespace Foo {
namespace Bar {
class Baz;
...
```
- in Ruby:
```
module Foo
module Bar
Baz = Google::Protobuf::DescriptorPool.generated_pool.lookup("Foo.Bar.Baz").msgclass
...
```

2. I'm not aware of protobuff syntax construct one could use to generate message name containing dot. And if message name cannot contain dot than there is no ambiguity: everything after the last dot is message name and everything before last dot is package name.

**Comment by tony612** [comment]
@predrag-rakic 
Other languages usually have packages(Go, Python) or modules(like Ruby) as namespaces. But Elixir don't have something like this. So it's a bit harder to handle this problem.

There're nested messages like
```
package foo;
message bar {
  message baz {}
}
```
And the module name will be `Foo.Bar` for `bar` and `Foo.Bar.Baz` for `baz`. But the package name is `foo`.

In fact, I thought about this problem for a long time months ago. In the end, I chose underscore. 😅 But I'm open to other ideas.

**Comment by tony612** [comment]
How about providing an option to support this feature? We can make the non-underscore as the default behavior(it fits Elixir style more) and support an option to change dots in package to underscore.

**Comment by tony612** [comment]
fixed by https://github.com/tony612/protobuf-elixir/commit/13cb6dec584f1fe7c0dbdb6df85c427f32832368

**Comment by uberbrodt** [comment]
@tony612  Sorry to comment on a closed issue, but did you end up providing some sort of option to keep the previous behaviour? I would also be interested in adding a package prefix. Eg. for the `Foo.Bar` message, I would like it to generate  `Protobuf.Foo.Bar`. Or even being able to specify it in the message, the way you can with Java https://developers.google.com/protocol-buffers/docs/reference/java-generated#package.

**Comment by tony612** [comment]
@uberbrodt I don't have plan to add option to support underscore because I think we'd better follow one convention. And I do have the plan to support prefix or custom package names.

**Comment by uberbrodt** [comment]
@tony612 Yeah, I can see your point. It's a bit of hassle when upgrading because all references and/or aliases need to be fixed in calling code. Might be worth making a note in the README.
